platform :ios, '9.0'
use_frameworks!

target 'FTMTableSectionModules_Example' do
  pod 'FTMTableSectionModules', :path => '../'
  pod 'FTMTableSectionModules/Tests', :path => '../'
  
  target 'FTMTableSectionModules_Tests' do
    inherit! :search_paths
    pod 'iOSSnapshotTestCase', :inhibit_warnings => true
  end
end
